#pragma once
#include "core/Types.hpp"

namespace uaro::net {

// On-wire length of a server->client packet id, from the server packet_db
// (PacketTable.cpp, generated by tools/gen_packet_table.py): >0 = fixed length,
// -1 = variable (a u16 total length sits at offset 2), 0 = unknown id. Used by
// the stream framer (net::nextPacket) to consume one packet at a time.
int packetDbLength(u16 id);

} // namespace uaro::net
