#include "net/SkillNames.hpp"

#include <unordered_map>

namespace uaro::net {

// internalName -> English display name, generated from roBrowser DB/Skills/SkillInfo.js
// (its Name -> SkillName pairs). ASCII-only: a couple of untranslated entries that
// carried raw EUC-KR names are dropped, so they fall back to the internal name.
std::string skillName(const std::string& internalName) {
    static const std::unordered_map<std::string, const char*> kNames = {
        {"SN_WINDWALK", "Wind Walk"},
        {"AL_RUWACH", "Ruwach"},
        {"WS_MELTDOWN", "Melt Down"},
        {"WS_CREATECOIN", "Create Coin"},
        {"MER_MAGNIFICAT", "Magnificat"},
        {"WS_CREATENUGGET", "Create Nugget"},
        {"WS_CARTBOOST", "Cart Boost"},
        {"WS_SYSTEMCREATE", "Auto Attack System"},
        {"ST_CHASEWALK", "Chase Walk"},
        {"ST_REJECTSWORD", "Reject Sword"},
        {"ST_STEALBACKPACK", "Steal Backpack"},
        {"EL_HEATER", "Heater"},
        {"CR_ALCHEMY", "Alchemy"},
        {"CR_SYNTHESISPOTION", "Synthesis Potion"},
        {"CG_ARROWVULCAN", "Arrow Vulcan"},
        {"CG_MOONLIT", "Moonlit Water Mill"},
        {"CG_MARIONETTE", "Marionette Control"},
        {"LK_SPIRALPIERCE", "Spiral Pierce"},
        {"LK_HEADCRUSH", "Head Crush"},
        {"LK_JOINTBEAT", "Joint Beat"},
        {"AL_PNEUMA", "Pneuma"},
        {"HW_NAPALMVULCAN", "Napalm Vulcan"},
        {"CH_SOULCOLLECT", "Dangerous Soul Collect"},
        {"PF_MINDBREAKER", "Mind Breaker"},
        {"PF_MEMORIZE", "Memorize"},
        {"PF_FOGWALL", "Wall of Fog"},
        {"PF_SPIDERWEB", "Spider Web"},
        {"ASC_METEORASSAULT", "Meteor Assault"},
        {"ASC_CDP", "Create Deadly Poison"},
        {"WE_BABY", "Mom, Dad, I love you!"},
        {"WE_CALLPARENT", "Mom, Dad, I miss you!"},
        {"WE_CALLBABY", "Come to me, honey~"},
        {"TK_RUN", "Running"},
        {"TK_READYSTORM", "Prepare Whirlwind Kick"},
        {"TK_STORMKICK", "Whirlwind Kick"},
        {"TK_READYDOWN", "Prepare Axe Kick"},
        {"TK_DOWNKICK", "Axe Kick"},
        {"AL_TELEPORT", "Teleportation"},
        {"TK_READYTURN", "Prepare Round Kick"},
        {"TK_TURNKICK", "Round Kick"},
        {"TK_READYCOUNTER", "Prepare Counter Kick"},
        {"TK_COUNTER", "Counter Kick"},
        {"TK_DODGE", "Break Fall"},
        {"TK_JUMPKICK", "Flying Side Kick"},
        {"TK_HPTIME", "Peaceful Rest"},
        {"TK_SPTIME", "Enjoyable Rest"},
        {"TK_POWER", "Fighting Chant"},
        {"TK_SEVENWIND", "Warm Wind"},
        {"TK_HIGHJUMP", "High Jump"},
        {"SG_FEEL", "Feeling"},
        {"SG_SUN_WARM", "Warmth of the Sun"},
        {"SG_MOON_WARM", "Warmth of the Moon"},
        {"SG_STAR_WARM", "Warmth of the Stars"},
        {"SG_SUN_COMFORT", "Comfort of the Sun"},
        {"AL_WARP", "Warp Portal"},
        {"SG_MOON_COMFORT", "Comfort of the Moon"},
        {"SG_STAR_COMFORT", "Comfort of the Stars"},
        {"SG_HATE", "Hatred"},
        {"SG_SUN_ANGER", "Anger of the Sun"},
        {"SG_MOON_ANGER", "Anger of the Moon"},
        {"SG_STAR_ANGER", "Anger of the Stars"},
        {"SG_SUN_BLESS", "Blessing of the Sun"},
        {"SG_MOON_BLESS", "Blessing of the Moon"},
        {"SG_STAR_BLESS", "Blessing of the Stars"},
        {"SG_DEVIL", "Demon"},
        {"GD_DEVELOPMENT", "Emsolute Develop"},
        {"SG_FRIEND", "Friend"},
        {"SG_KNOWLEDGE", "Knowledge"},
        {"SG_FUSION", "Union"},
        {"SL_ALCHEMIST", "Alchemist Spirit"},
        {"AM_BERSERKPITCHER", "Berserk Pitcher"},
        {"SL_MONK", "Monk Spirit"},
        {"AL_HEAL", "Heal"},
        {"SL_STAR", "Star Gladiator Spirit"},
        {"SL_SAGE", "Sage Spirit"},
        {"MER_QUICKEN", "Two-Hand Quicken"},
        {"SL_CRUSADER", "Crusader Spirit"},
        {"SL_SUPERNOVICE", "Super Novice Spirit"},
        {"SL_KNIGHT", "Knight Spirit"},
        {"SL_WIZARD", "Wizard Spirit"},
        {"SL_PRIEST", "Priest Spirit"},
        {"SL_BARDDANCER", "Bard and Dancer Spirits"},
        {"EL_TROPIC", "Tropic"},
        {"SL_ROGUE", "Rogue Spirit"},
        {"SL_ASSASIN", "Assassin Spirit"},
        {"SL_BLACKSMITH", "Blacksmith Spirit"},
        {"BS_ADRENALINE2", "Full Adrenaline Rush"},
        {"SL_HUNTER", "Hunter Spirit"},
        {"SL_SOULLINKER", "Soul Linker Spirit"},
        {"SL_KAIZEL", "Kaizel"},
        {"SL_KAAHI", "Kaahi"},
        {"AL_INCAGI", "Increase Agility"},
        {"SL_KAUPE", "Kaupe"},
        {"SL_KAITE", "Kaite"},
        {"SL_KAINA", "Kaina"},
        {"SL_STIN", "Estin"},
        {"SL_STUN", "Estun"},
        {"SL_SMA", "Esma"},
        {"SL_SWOO", "Eswoo"},
        {"SL_SKE", "Eske"},
        {"SL_SKA", "Eska"},
        {"ST_PRESERVE", "Preserve"},
        {"ST_FULLSTRIP", "Full Strip"},
        {"WS_WEAPONREFINE", "Weapon Refine"},
        {"CR_SLIMPITCHER", "Slim Potion Pitcher"},
        {"CR_FULLPROTECTION", "Full Chemical Protection"},
        {"AL_DECAGI", "Decrease Agility"},
        {"PA_SHIELDCHAIN", "Shield Chain"},
        {"HP_MANARECHARGE", "Mana Recharge"},
        {"PF_DOUBLECASTING", "Double Casting"},
        {"HW_GANBANTEIN", "Ganbantein"},
        {"HW_GRAVITATION", "Gravitation Field"},
        {"WS_CARTTERMINATION", "Cart Termination"},
        {"WS_OVERTHRUSTMAX", "Maximum Over Thrust"},
        {"CG_LONGINGFREEDOM", "Longing for Freedom"},
        {"CG_HERMODE", "Wand of Hermode"},
        {"CG_TAROTCARD", "Tarot Card of Fate"},
        {"CR_ACIDDEMONSTRATION", "Acid Demonstration"},
        {"CR_CULTIVATION", "Plant Cultivation"},
        {"TK_MISSION", "TaeKwon Mission"},
        {"SL_HIGH", "Rebirth Spirit"},
        {"KN_ONEHAND", "One-Hand Quicken"},
        {"AL_HOLYWATER", "Aqua Benedicta"},
        {"AM_TWILIGHT1", "Twilight Alchemy"},
        {"AM_TWILIGHT2", "Twilight Alchemy"},
        {"AM_TWILIGHT3", "Twilight Alchemy"},
        {"HT_POWER", "Beast Strafing"},
        {"GS_GLITTERING", "Flip the Coin"},
        {"RK_ENCHANTBLADE", "Enchant Blade"},
        {"GS_FLING", "Fling"},
        {"RK_WINDCUTTER", "Wind Cutter"},
        {"GS_TRIPLEACTION", "Triple Action"},
        {"RK_DRAGONHOWLING", "Dragon Howling"},
        {"GS_BULLSEYE", "Bull's Eye"},
        {"RK_REFRESH", "Refresh"},
        {"GS_MADNESSCANCEL", "Madness Canceller"},
        {"RK_STORMBLAST", "Storm Blast"},
        {"GS_ADJUSTMENT", "Adjustment"},
        {"GC_VENOMIMPRESS", "Venom Impress"},
        {"GS_INCREASING", "Increasing Accuracy"},
        {"GC_CREATENEWPOISON", "Create New Poison"},
        {"GS_MAGICALBULLET", "Magical Bullet"},
        {"GC_COUNTERSLASH", "Counter Slash"},
        {"GS_CRACKER", "Cracker"},
        {"GC_CLOAKINGEXCEED", "Cloaking Exceed"},
        {"GS_SINGLEACTION", "Single Action"},
        {"GC_CROSSRIPPERSLASHER", "Cross Ripper Slasher"},
        {"GS_SNAKEEYE", "Snake's Eye"},
        {"AB_CLEMENTIA", "Clementia"},
        {"SM_SWORD", "Sword Mastery"},
        {"AL_CRUCIS", "Signum Crucis"},
        {"GS_TRACKING", "Tracking"},
        {"GS_DISARM", "Disarm"},
        {"GS_PIERCINGSHOT", "Piercing Shot"},
        {"GS_RAPIDSHOWER", "Rapid Shower"},
        {"GS_DESPERADO", "Desperado"},
        {"GS_GATLINGFEVER", "Gatling Fever"},
        {"GS_DUST", "Dust"},
        {"GS_FULLBUSTER", "Full Buster"},
        {"GS_SPREADATTACK", "Spread Attack"},
        {"GS_GROUNDDRIFT", "Ground Drift"},
        {"NJ_TOBIDOUGU", "Throwing Mastery"},
        {"NJ_SYURIKEN", "Throw Shuriken"},
        {"NJ_KUNAI", "Throw Kunai"},
        {"NJ_HUUMA", "Throw Fuuma Shuriken"},
        {"NJ_ZENYNAGE", "Throw Zeny"},
        {"AL_ANGELUS", "Angelus"},
        {"NJ_KASUMIKIRI", "Mist Slash"},
        {"NJ_SHADOWJUMP", "Shadow Jump"},
        {"NJ_KIRIKAGE", "Shadow Slash"},
        {"NJ_UTSUSEMI", "Cast-off Ciceda Shell"},
        {"NJ_BUNSINJYUTSU", "Illusionary Shadow"},
        {"NJ_NINPOU", "Ninpou Training"},
        {"NJ_KOUENKA", "Crimson Fire Blossom"},
        {"NJ_KAENSIN", "Crimson Fire Formation"},
        {"NJ_BAKUENRYU", "Dragon Fire Formation"},
        {"NJ_HYOUSENSOU", "Lightning Spear of Ice"},
        {"NJ_SUITON", "Water Escape Technique"},
        {"NJ_HYOUSYOURAKU", "Falling Ice Pillar"},
        {"NJ_HUUJIN", "Wind Blade"},
        {"NJ_RAIGEKISAI", "Lightning Crash"},
        {"NJ_KAMAITACHI", "North Wind"},
        {"AL_BLESSING", "Blessing"},
        {"NJ_ISSEN", "Final Strike"},
        {"MB_FIGHTING", "Munak Fighting"},
        {"MB_NEUTRAL", "Bongun Neutral"},
        {"MB_TAIMING_PUTI", "Pet Friend"},
        {"MB_WHITEPOTION", "Ordering White Potion"},
        {"MB_MENTAL", "Ordering Mental"},
        {"MB_CARDPITCHER", "Card Pitcher"},
        {"MB_PETPITCHER", "Pet Pitcher"},
        {"MB_BODYSTUDY", "Body Studying"},
        {"MB_BODYALTER", "Body Altering"},
        {"MB_PETMEMORY", "Pet Memory"},
        {"MB_M_TELEPORT", "Munak Teleport"},
        {"MB_B_GAIN", "Bongun Gain"},
        {"MB_M_GAIN", "Munak Gain"},
        {"MB_MISSION", "Taming Mission"},
        {"AL_CURE", "Cure"},
        {"MB_MUNAKBALL", "Munak Ball"},
        {"MB_SCROLL", "Bongun Scroll"},
        {"MB_B_GATHERING", "Bongun Gathering"},
        {"MB_M_GATHERING", "Munak Gathering"},
        {"MB_B_EXCLUDE", "Bongun Exclude"},
        {"MB_B_DRIFT", "Bongun Drift"},
        {"MB_B_WALLRUSH", "Bongun Wall Rush"},
        {"MB_M_WALLRUSH", "Munak Wall Rush"},
        {"MB_B_WALLSHIFT", "Bongun Wall Shift"},
        {"MB_M_WALLCRASH", "Munak Wall Crash"},
        {"MB_M_REINCARNATION", "Munak Reincarnation"},
        {"MB_B_EQUIP", "Bongun Almighty"},
        {"SL_DEATHKNIGHT", "Death Knight Spirit"},
        {"SL_COLLECTOR", "Dark Collector Spirit"},
        {"SL_NINJA", "Ninja Spirit"},
        {"MC_INCCARRY", "Enlarge Weight Limit"},
        {"AM_TWILIGHT4", "Twilight Alchemy"},
        {"DE_BERSERKAIZER", "Berserk Kaizer"},
        {"DA_DARKPOWER", "Dark Soul Power"},
        {"DE_PASSIVE", "Death Passive"},
        {"DE_PATTACK", "Death Passive Attack"},
        {"DE_PSPEED", "Death Passive Speed"},
        {"DE_PDEFENSE", "Death Passive Defense"},
        {"DE_PCRITICAL", "Death Passive Critical"},
        {"DE_PHP", "Death Passive HP"},
        {"DE_PSP", "Death Passive SP"},
        {"DE_RESET", "Death Optimize"},
        {"DE_RANKING", "Death Ranking"},
        {"DE_PTRIPLE", "Death Passive Triple"},
        {"DE_ENERGY", "Death Energy"},
        {"MC_DISCOUNT", "Discount"},
        {"DE_SLASH", "Death Slash"},
        {"DE_COIL", "Death Coil"},
        {"DE_WAVE", "Death Wave"},
        {"DE_REBIRTH", "Death Reverse Energy"},
        {"DE_AURA", "Death Aura"},
        {"DE_FREEZER", "Death Freezer"},
        {"DE_CHANGEATTACK", "Death Change Attack"},
        {"DE_PUNISH", "Death Punish"},
        {"DE_POISON", "Death Poison Slash"},
        {"DE_INSTANT", "Death Instant Barrier"},
        {"DE_WARNING", "Death Warning"},
        {"DE_RANKEDKNIFE", "Death Knife"},
        {"DE_RANKEDGRADIUS", "Death Gradius"},
        {"DE_GAUGE", "Mighty Gauge"},
        {"DE_GTIME", "Mighty Time Charge"},
        {"MC_OVERCHARGE", "Overcharge"},
        {"DE_GSKILL", "Mighty Skill Charge"},
        {"DE_GKILL", "Mighty Kill Charge"},
        {"DE_ACCEL", "Dead Acceleration"},
        {"DE_BLOCKDOUBLE", "Dead Double Blocking"},
        {"DE_BLOCKMELEE", "Dead Near(Melee) Blocking"},
        {"DE_BLOCKFAR", "Dead Distance(Range) Blocking"},
        {"DE_FRONTATTACK", "Dead Rush Attack"},
        {"DE_DANGERATTACK", "Dead Dangerous Attack"},
        {"DE_TWINATTACK", "Dead Twin Attack"},
        {"DE_WINDATTACK", "Dead Storm Attack"},
        {"DE_WATERATTACK", "Dead Water Attack"},
        {"DA_ENERGY", "Dark Energy"},
        {"DA_CLOUD", "Dark Cloud"},
        {"DA_FIRSTSLOT", "Dark First Fantasy"},
        {"DA_HEADDEF", "Dark Head Defense"},
        {"MC_PUSHCART", "Pushcart"},
        {"DA_TRANSFORM", "Dark Transform"},
        {"DA_EXPLOSION", "Dark Explosion"},
        {"DA_REWARD", "Dark Reward"},
        {"DA_CRUSH", "Dark Crush"},
        {"DA_ITEMREBUILD", "Dark Item Rebuild"},
        {"DA_ILLUSION", "Dark Illusion"},
        {"DA_NUETRALIZE", "Dark Nuetralize"},
        {"DA_RUNNER", "Dark Runner"},
        {"DA_TRANSFER", "Dark Transfer"},
        {"DA_WALL", "Dark Wall"},
        {"RETURN_TO_ELDICASTES", "Return to Eldicastes"},
        {"DA_REVENGE", "Dark Revenge"},
        {"DA_EARPLUG", "Dark Ear Plug"},
        {"DA_CONTRACT", "Black Gemstone Contract"},
        {"DA_BLACK", "Black Gemstone Magic"},
        {"MC_IDENTIFY", "Identify"},
        {"DA_MAGICCART", "Collector Magic Cart"},
        {"DA_COPY", "Collector Copy"},
        {"DA_CRYSTAL", "Collector Crystal"},
        {"DA_EXP", "Collector Experience"},
        {"DA_CARTSWING", "Collector Magical Cart Swing"},
        {"DA_REBUILD", "Collector Human Rebuild"},
        {"DA_JOBCHANGE", "Collector Novice Job Change"},
        {"DA_EDARKNESS", "Collector Emperium Darkness"},
        {"DA_EGUARDIAN", "Collector Emperium Guardian"},
        {"DA_TIMEOUT", "Collector Time Out"},
        {"ALL_TIMEIN", "Time In"},
        {"DA_ZENYRANK", "Collector Ranking"},
        {"DA_ACCESSORYMIX", "Collector  Mix"},
        {"NPC_EARTHQUAKE", "Earth Quake"},
        {"EL_CIRCLE_OF_FIRE", "Circle of Fire"},
        {"MC_VENDING", "Vending"},
        {"EL_TIDAL_WEAPON", "Tidal Weapon"},
        {"NPC_DRAGONFEAR", "Dragon Fear"},
        {"NPC_PULSESTRIKE", "Pulse Strike"},
        {"NPC_HELLJUDGEMENT", "Hell Judgement"},
        {"NPC_WIDESILENCE", "Wide Silence"},
        {"NPC_WIDEFREEZE", "Wide Freeze"},
        {"NPC_WIDEBLEEDING", "Wide Bleeding"},
        {"NPC_WIDESTONE", "Wide Stone"},
        {"NPC_WIDECONFUSE", "Wide Confuse"},
        {"NPC_WIDESLEEP", "Wide Sleep"},
        {"NPC_EVILLAND", "Evil Land"},
        {"MC_MAMMONITE", "Mammonite"},
        {"NPC_SLOWCAST", "Slow Cast"},
        {"NPC_CRITICALWOUND", "Critical Wound"},
        {"NPC_STONESKIN", "Stone Skin"},
        {"NPC_ANTIMAGIC", "Anti Magic"},
        {"NPC_WIDECURSE", "Wide Curse"},
        {"NPC_WIDESTUN", "Wide Stun"},
        {"NPC_VAMPIRE_GIFT", "Vampire Gift"},
        {"NPC_WIDESOULDRAIN", "Wide Soul Drain"},
        {"ALL_INCCARRY", "Enlarge Weight Limit R"},
        {"NPC_HELLPOWER", "Hell Power"},
        {"AC_OWL", "Owl's Eye"},
        {"GM_SANDMAN", "Goodnight, Sweetie"},
        {"ALL_CATCRY", "Crying Monster"},
        {"ALL_PARTYFLEE", "Blow! Flower Wind"},
        {"ALL_ANGEL_PROTECT", "Thank You"},
        {"ALL_DREAM_SUMMERNIGHT", "A Dream Of Summer Night"},
        {"ALL_REVERSEORCISH", "Reverse Orcish"},
        {"ALL_WEWISH", "We Wish"},
        {"AC_VULTURE", "Vulture's Eye"},
        {"AC_CONCENTRATION", "Attention Concentrate"},
        {"AC_DOUBLE", "Double Strafing"},
        {"HLIF_HEAL", "Touch of Heal"},
        {"HFLI_MOON", "Moonlight"},
        {"MH_XENO_SLASHER", "Xeno Slasher"},
        {"MH_STEINWAND", "Stone Wall"},
        {"MH_LAVA_SLIDE", "Lava Slide"},
        {"AC_SHOWER", "Arrow Shower"},
        {"GD_KAFRACONTRACT", "Kafra Contract"},
        {"SM_TWOHAND", "Two-Handed Sword Mastery"},
        {"TF_DOUBLE", "Double Attack"},
        {"MA_LANDMINE", "Land Mine"},
        {"MER_REGAIN", "Regain"},
        {"EL_FIRE_CLOAK", "Fire Cloak"},
        {"TF_MISS", "Increase Dodge"},
        {"EL_WIND_SLASH", "Wind Slash"},
        {"TF_STEAL", "Steal"},
        {"TF_HIDING", "Hiding"},
        {"TF_POISON", "Envenom"},
        {"TF_DETOXIFY", "Detoxify"},
        {"ALL_RESURRECTION", "Resurrection"},
        {"KN_SPEARMASTERY", "Spear Mastery"},
        {"GD_GUARDRESEARCH", "Guardian Research"},
        {"KN_PIERCE", "Pierce"},
        {"MA_SANDMAN", "Sandman"},
        {"MER_TENDER", "Tender"},
        {"EL_FIRE_MANTLE", "Fire Mantle"},
        {"KN_BRANDISHSPEAR", "Brandish Spear"},
        {"EL_HURRICANE", "Hurricane"},
        {"KN_SPEARSTAB", "Spear Stab"},
        {"KN_SPEARBOOMERANG", "Spear Boomerang"},
        {"KN_TWOHANDQUICKEN", "Two-Hand Quicken"},
        {"KN_AUTOCOUNTER", "Auto Counter"},
        {"KN_BOWLINGBASH", "Bowling Bash"},
        {"KN_CHARGEATK", "Charge Attack"},
        {"CR_SHRINK", "Shrink"},
        {"AS_SONICACCEL", "Sonic Acceleration"},
        {"AS_VENOMKNIFE", "Throw Venom Knife"},
        {"RG_CLOSECONFINE", "Close Confine"},
        {"WZ_SIGHTBLASTER", "Sight Blaster"},
        {"KN_RIDING", "Riding"},
        {"SA_ELEMENTWATER", "Elemental Change (Water)"},
        {"HT_PHANTASMIC", "Phantasmic Arrow"},
        {"BA_PANGVOICE", "Pang Voice"},
        {"DC_WINKCHARM", "Wink of Charm"},
        {"BS_UNFAIRLYTRICK", "Unfair Trick"},
        {"BS_GREED", "Greed"},
        {"PR_REDEMPTIO", "Redemptio"},
        {"MO_KITRANSLATION", "Ki Translation"},
        {"MO_BALKYOUNG", "Ki Explosion"},
        {"SA_ELEMENTGROUND", "Elemental Change (Earth)"},
        {"SA_ELEMENTFIRE", "Elemental Change (Fire)"},
        {"SA_ELEMENTWIND", "Elemental Change (Wind)"},
        {"SM_RECOVERY", "Increase Recuperative Power"},
        {"KN_CAVALIERMASTERY", "Cavalry Mastery"},
        {"AB_HIGHNESSHEAL", "Highness Heal"},
        {"AB_DUPLELIGHT_MELEE", "Duple Light (Melee)"},
        {"MER_BENEDICTION", "Benediction"},
        {"PR_MACEMASTERY", "Mace Mastery"},
        {"EL_WATER_SCREEN", "Water Screen"},
        {"PR_IMPOSITIO", "Impositio Manus"},
        {"EL_HURRICANE_ATK", "Hurricane"},
        {"PR_SUFFRAGIUM", "Suffragium"},
        {"PR_ASPERSIO", "Aspersio"},
        {"PR_BENEDICTIO", "B.S Sacramenti"},
        {"WL_SIENNAEXECRATE", "Sienna Execrate"},
        {"WL_CRIMSONROCK", "Crimson Rock"},
        {"WL_SUMMONBL", "Summon Lightning Ball"},
        {"WL_READING_SB", "Reading Spellbook"},
        {"PR_SANCTUARY", "Sanctuary"},
        {"RA_CLUSTERBOMB", "Cluster Bomb"},
        {"RA_WUGSTRIKE", "Warg Strike"},
        {"RA_CAMOUFLAGE", "Camouflage"},
        {"RA_MAIZETRAP", "Maize Trap"},
        {"NC_MADOLICENCE", "Magic Gear License"},
        {"NC_FLAMELAUNCHER", "Flare Launcher"},
        {"NC_HOVERING", "Hovering"},
        {"PR_SLOWPOISON", "Slow Poison"},
        {"NC_ANALYZE", "Analyze"},
        {"NC_REPAIR", "Repair"},
        {"NC_POWERSWING", "Power Swing"},
        {"NC_DISJOINT", "FAW - Removal"},
        {"SC_SHADOWFORM", "Shadow Form"},
        {"SC_DEADLYINFECT", "Deadly Infect"},
        {"SC_LAZINESS", "Masquerade - Lazieness"},
        {"PR_STRECOVERY", "Recovery"},
        {"SC_BLOODYLUST", "Bloody Lust"},
        {"LG_CANNONSPEAR", "Cannon Spear"},
        {"LG_REFLECTDAMAGE", "Reflect Damage"},
        {"LG_SHIELDSPELL", "Shield Spell"},
        {"LG_BANDING", "Banding"},
        {"LG_EARTHDRIVE", "Earth Drive"},
        {"SR_SKYNETBLOW", "Skynet Blow"},
        {"PR_KYRIE", "Kyrie Eleison"},
        {"SR_LIGHTNINGWALK", "Lightning Walk"},
        {"SR_GATEOFHELL", "Gate of Hell"},
        {"SR_GENTLETOUCH_CHANGE", "Gentle Touch (Change)"},
        {"WA_SYMPHONY_OF_LOVER", "Symphony of Lovers"},
        {"PR_MAGNIFICAT", "Magnificat"},
        {"MI_HARMONIZE", "Harmonize"},
        {"PR_GLORIA", "Gloria"},
        {"WM_POEMOFNETHERWORLD", "Poem of the Netherworld"},
        {"WM_SIRCLEOFNATURE", "Circle of Life's Melody"},
        {"PR_LEXDIVINA", "Lex Divina"},
        {"WM_LERADS_DEW", "Lerad's Dew"},
        {"SO_FIREWALK", "Fire Walk"},
        {"SO_DIAMONDDUST", "Diamond Dust"},
        {"SO_STRIKING", "Striking"},
        {"SO_ARRULLO", "Arrullo"},
        {"PR_TURNUNDEAD", "Turn Undead"},
        {"SO_EL_SYMPATHY", "Spirit Sympathy"},
        {"SO_WIND_INSIGNIA", "Wind Insignia"},
        {"GN_REMODELING_CART", "Cart Remodeling"},
        {"GN_THORNS_TRAP", "Thorn Trap"},
        {"GN_CRAZYWEED", "Crazy Weed"},
        {"PR_LEXAETERNA", "Lex Aeterna"},
        {"GN_MIX_COOKING", "Mix Cooking"},
        {"GD_EXTENSION", "Guild Extension"},
        {"AB_SECRAMENT", "Sacrament"},
        {"PR_MAGNUS", "Magnus Exorcismus"},
        {"ALL_BUYING_STORE", "Open Buying Store"},
        {"SM_BASH", "Bash"},
        {"WZ_FIREPILLAR", "Fire Pillar"},
        {"MA_REMOVETRAP", "Remove Trap"},
        {"MER_RECUPERATE", "Recuperate"},
        {"WZ_SIGHTRASHER", "Sightrasher"},
        {"EL_WATER_DROP", "Water Drop"},
        {"WZ_FIREIVY", "Fire Ivy"},
        {"EL_TYPOON_MIS", "Typhoon Missile"},
        {"WZ_METEOR", "Meteor Storm"},
        {"WZ_JUPITEL", "Jupitel Thunder"},
        {"WZ_VERMILION", "Lord of Vermilion"},
        {"WZ_WATERBALL", "Water Ball"},
        {"WZ_ICEWALL", "Ice Wall"},
        {"WZ_FROSTNOVA", "Frost Nova"},
        {"WZ_STORMGUST", "Storm Gust"},
        {"WZ_EARTHSPIKE", "Earth Spike"},
        {"WZ_HEAVENDRIVE", "Heaven's Drive"},
        {"WZ_QUAGMIRE", "Quagmire"},
        {"WZ_ESTIMATION", "Monster Property"},
        {"HLIF_BRAIN", "Brain Surgery"},
        {"HFLI_SPEED", "Over Speed"},
        {"MH_NEEDLE_OF_PARALYZE", "Needle of Paralyze"},
        {"MH_STYLE_CHANGE", "Style Change"},
        {"MH_ANGRIFFS_MODUS", "Attack Mode"},
        {"MH_VOLCANIC_ASH", "Volcanic Ash"},
        {"BS_IRON", "Iron Tempering"},
        {"GD_GLORYGUILD", "Guild's Glory"},
        {"BS_STEEL", "Steel Tempering"},
        {"SM_PROVOKE", "Provoke"},
        {"BS_ENCHANTEDSTONE", "Enchanted Stone Craft"},
        {"MA_CHARGEARROW", "Charge Arrow"},
        {"MER_MENTALCURE", "Mental Cure"},
        {"BS_ORIDEOCON", "Research Oridecon"},
        {"EL_WATER_BARRIER", "Water Barrier"},
        {"BS_DAGGER", "Smith Dagger"},
        {"EL_TYPOON_MIS_ATK", "Typhoon Missile"},
        {"BS_SWORD", "Smith Sword"},
        {"BS_TWOHANDSWORD", "Smith Two-Handed Sword"},
        {"BS_AXE", "Smith Axe"},
        {"BS_MACE", "Smith Mace"},
        {"BS_KNUCKLE", "Smith Brass Knuckle"},
        {"BS_SPEAR", "Smith Spear"},
        {"BS_HILTBINDING", "Hilt Binding"},
        {"BS_FINDINGORE", "Finding Ore"},
        {"BS_WEAPONRESEARCH", "Weaponry Research"},
        {"BS_REPAIRWEAPON", "Repair Weapon"},
        {"BS_SKINTEMPER", "Skin Tempering"},
        {"BS_HAMMERFALL", "Hammer Fall"},
        {"GD_LEADERSHIP", "Great Leadership"},
        {"BS_ADRENALINE", "Adrenaline Rush"},
        {"SM_MAGNUM", "Magnum Break"},
        {"BS_WEAPONPERFECT", "Weapon Perfection"},
        {"MA_SHARPSHOOTING", "Sharp Shooting"},
        {"MER_COMPRESS", "Compress"},
        {"BS_OVERTHRUST", "Over Thrust"},
        {"EL_WIND_STEP", "Wind Step"},
        {"BS_MAXIMIZE", "Maximize Power"},
        {"EL_STONE_HAMMER", "Stone Hammer"},
        {"HT_SKIDTRAP", "Skid Trap"},
        {"HT_LANDMINE", "Land Mine"},
        {"HT_ANKLESNARE", "Ankle Snare"},
        {"HT_SHOCKWAVE", "Shockwave Trap"},
        {"HT_SANDMAN", "Sandman"},
        {"HT_FLASHER", "Flasher"},
        {"HT_FREEZINGTRAP", "Freezing Trap"},
        {"HT_BLASTMINE", "Blast Mine"},
        {"HT_CLAYMORETRAP", "Claymore Trap"},
        {"HT_REMOVETRAP", "Remove Trap"},
        {"HT_TALKIEBOX", "Talkie Box"},
        {"RK_SONICWAVE", "Sonic Wave"},
        {"RK_HUNDREDSPEAR", "Hundred Spear"},
        {"RK_IGNITIONBREAK", "Ignition Break"},
        {"RK_DRAGONBREATH", "Dragon Breath"},
        {"RK_RUNEMASTERY", "Rune Mastery"},
        {"RK_CRUSHSTRIKE", "Crush Strike"},
        {"HT_BEASTBANE", "Beast Bane"},
        {"RK_VITALITYACTIVATION", "Vitality Activation"},
        {"RK_FIGHTINGSPIRIT", "Fightning Spirit"},
        {"RK_PHANTOMTHRUST", "Phantom Thrust"},
        {"GC_CROSSIMPACT", "Cross Impact"},
        {"GC_RESEARCHNEWPOISON", "Research New Poison"},
        {"GC_ANTIDOTE", "Antidote"},
        {"GC_WEAPONBLOCKING", "Weapon Blocking"},
        {"HT_FALCON", "Falconry Mastery"},
        {"GC_POISONSMOKE", "Poison Smoke"},
        {"GC_PHANTOMMENACE", "Phantom Menace"},
        {"GC_ROLLINGCUTTER", "Rolling Cutter"},
        {"AB_JUDEX", "Judex"},
        {"AB_ADORAMUS", "Adoramus"},
        {"AB_CANTO", "Canto Candidus"},
        {"SM_ENDURE", "Endure"},
        {"HT_STEELCROW", "Steel Crow"},
        {"AB_LAUDARAMUS", "Lauda Ramus"},
        {"AB_CLEARANCE", "Clearance"},
        {"AB_DUPLELIGHT_MAGIC", "Duple Light (Magic)"},
        {"HT_BLITZBEAT", "Blitz Beat"},
        {"HT_DETECTING", "Detecting"},
        {"HT_SPRINGTRAP", "Spring Trap"},
        {"EL_WIND_CURTAIN", "Wind Curtain"},
        {"AS_RIGHT", "Right-Hand Mastery"},
        {"EL_ROCK_CRUSHER", "Rock Crusher"},
        {"AS_LEFT", "Left-Hand Mastery"},
        {"AS_KATAR", "Katar Mastery"},
        {"AS_CLOAKING", "Cloaking"},
        {"AS_SONICBLOW", "Sonic Blow"},
        {"AS_GRIMTOOTH", "Grimtooth"},
        {"AS_ENCHANTPOISON", "Enchant Poison"},
        {"WL_RADIUS", "Radius"},
        {"WL_HELLINFERNO", "Hell Inferno"},
        {"WL_EARTHSTRAIN", "Earth Strain"},
        {"AS_POISONREACT", "Poison React"},
        {"WL_SUMMONWB", "Summon Water Ball"},
        {"WL_FREEZE_SP", "Freeze Spell"},
        {"AS_VENOMDUST", "Venom Dust"},
        {"RA_WUGMASTERY", "Warg Mastery"},
        {"RA_WUGBITE", "Warg Bite"},
        {"RA_RESEARCHTRAP", "Research Trap"},
        {"AS_SPLASHER", "Venom Splasher"},
        {"NC_BOOSTKNUCKLE", "Boost Knuckle"},
        {"NC_COLDSLOWER", "Cold Slower"},
        {"NC_F_SIDESLIDE", "Front Side Slide"},
        {"NV_FIRSTAID", "First Aid"},
        {"NC_MAGNETICFIELD", "Magnetic Field"},
        {"NC_TRAININGAXE", "Axe Training"},
        {"NC_AXETORNADO", "Axe Tornado"},
        {"NV_TRICKDEAD", "Trick Dead"},
        {"SC_TRIANGLESHOT", "Triangle Shot"},
        {"SC_ENERVATION", "Masquerade - Enervation"},
        {"MG_SRECOVERY", "Increase Spiritual Power"},
        {"SM_MOVINGRECOVERY", "Moving HP Recovery"},
        {"SC_FEINTBOMB", "Feint Bomb"},
        {"LG_BANISHINGPOINT", "Banishing Point"},
        {"LG_PINPOINTATTACK", "Pinpoint Attack"},
        {"SM_FATALBLOW", "Fatal Blow"},
        {"LG_MOONSLASHER", "Moon Slasher"},
        {"LG_HESPERUSLIT", "Hesperuslit"},
        {"SR_EARTHSHAKER", "Earth Shaker"},
        {"SM_AUTOBERSERK", "Auto Berserk"},
        {"SR_KNUCKLEARROW", "Knuckle Arrow"},
        {"SR_ASSIMILATEPOWER", "Assimilate Power"},
        {"SR_GENTLETOUCH_QUIET", "Gentle Touch (Quiet)"},
        {"AC_MAKINGARROW", "Making Arrow"},
        {"WA_MOONLIT_SERENADE", "Moonlight Serenade"},
        {"AC_CHARGEARROW", "Charge Arrow"},
        {"TF_SPRINKLESAND", "Sprinkle Sand"},
        {"TF_BACKSLIDING", "Back Sliding"},
        {"TF_PICKSTONE", "Pick Stone"},
        {"WM_VOICEOFSIREN", "Siren's Voice"},
        {"WM_RANDOMIZESPELL", "Randomize Spell"},
        {"TF_THROWSTONE", "Throw Stone"},
        {"WM_MELODYOFSINK", "Melody of Sink"},
        {"MC_CARTREVOLUTION", "Cart Revolution"},
        {"SO_POISON_BUSTER", "Poison Buster"},
        {"SO_WARMER", "Warmer"},
        {"SO_EL_CONTROL", "Spirit Control"},
        {"MC_CHANGECART", "Change Cart"},
        {"SO_EL_CURE", "Spirit Recovery"},
        {"SO_EARTH_INSIGNIA", "Earth Insignia"},
        {"MC_LOUD", "Loud Exclamation"},
        {"GN_BLOOD_SUCKER", "Blood Sucker"},
        {"AL_HOLYLIGHT", "Holy Light"},
        {"GN_MAKEBOMB", "Create Bomb"},
        {"GD_SOULCOLD", "Soul of Cold"},
        {"MG_ENERGYCOAT", "Energy Coat"},
        {"ALL_GUARDIAN_RECALL", "Guardian Recall"},
        {"MG_SIGHT", "Sight"},
        {"MS_BASH", "Bash"},
        {"ML_BRANDISH", "Brandish Spear"},
        {"MER_AUTOBERSERK", "Auto Berserk"},
        {"EL_ZEPHYR", "Zephyr"},
        {"EL_FIRE_ARROW", "Fire Arrow"},
        {"EL_ROCK_CRUSHER_ATK", "Rock Crusher"},
        {"MG_NAPALMBEAT", "Napalm Beat"},
        {"HAMI_CASTLE", "Castling"},
        {"HVAN_CAPRICE", "Caprice"},
        {"MH_PAIN_KILLER", "Pain Killer"},
        {"MH_SILVERVEIN_RUSH", "Silver Bain Rush"},
        {"MH_CBC", "Continual Break Combo"},
        {"GD_HAWKEYES", "Sharp Hawk Eyes"},
        {"MG_SAFETYWALL", "Safety Wall"},
        {"MS_MAGNUM", "Magnum Break"},
        {"ML_SPIRALPIERCE", "Spiral Pierce"},
        {"MER_DECAGI", "Decrease Agility"},
        {"EL_SOLID_SKIN", "Solid Skin"},
        {"EL_FIRE_BOMB", "Fire Bomb"},
        {"EL_STONE_RAIN", "Stone Rain"},
        {"MG_SOULSTRIKE", "Soul Strike"},
        {"RG_SNATCHER", "Snatcher"},
        {"RG_STEALCOIN", "Steal Coin"},
        {"RG_BACKSTAP", "Back Stab"},
        {"RG_TUNNELDRIVE", "Tunnel Drive"},
        {"RG_RAID", "Raid"},
        {"RG_STRIPWEAPON", "Strip Weapon"},
        {"RG_STRIPSHIELD", "Strip Shield"},
        {"RG_STRIPARMOR", "Strip Armor"},
        {"RG_STRIPHELM", "Strip Helm"},
        {"RG_INTIMIDATE", "Intimidate"},
        {"RG_GRAFFITI", "Graffiti"},
        {"GD_BATTLEORDER", "Battle Orders"},
        {"RG_FLAGGRAFFITI", "Flag Graffiti"},
        {"RG_CLEANER", "Cleaner"},
        {"RG_GANGSTER", "Gangster's Paradise"},
        {"GD_ITEMEMERGENCYCALL", "Item Emergency Call"},
        {"MG_COLDBOLT", "Cold Bolt"},
        {"RG_COMPULSION", "Compulsion Discount"},
        {"DE_GPAIN", "Mighty Pain Charge"},
        {"MS_BOWLINGBASH", "Bowling Bash"},
        {"ML_DEFENDER", "Defender"},
        {"RG_PLAGIARISM", "Plagiarism"},
        {"SR_DRAGONCOMBO", "Dragon Combo"},
        {"SC_STRIPACCESSARY", "Strip Accessory"},
        {"GD_GLORYWOUNDS", "Wounds of Glory"},
        {"AM_AXEMASTERY", "Axe Mastery"},
        {"GD_GUARDUP", "Build up the Guardian"},
        {"GD_APPROVAL", "Approval"},
        {"MER_INCAGI", "Increase Agility"},
        {"AM_LEARNINGPOTION", "Learning Potion"},
        {"MER_BLESSING", "Blessing"},
        {"MER_KYRIE", "Kyrie Eleison"},
        {"EL_STONE_SHIELD", "Stone Shield"},
        {"AM_PHARMACY", "Pharmacy"},
        {"MER_ESTIMATION", "Monster Property"},
        {"MER_LEXDIVINA", "Lex Divina"},
        {"MER_SCAPEGOAT", "Scapegoat"},
        {"AM_DEMONSTRATION", "Demonstration"},
        {"MER_PROVOKE", "Provoke"},
        {"MER_CRASH", "Crash"},
        {"MER_SIGHT", "Sight"},
        {"AM_ACIDTERROR", "Acid Terror"},
        {"LG_SHIELDPRESS", "Shield Press"},
        {"ML_AUTOGUARD", "Auto Guard"},
        {"ML_PIERCE", "Pierce"},
        {"AM_POTIONPITCHER", "Potion Pitcher"},
        {"MA_FREEZINGTRAP", "Freezing Trap"},
        {"MA_SKIDTRAP", "Skid Trap"},
        {"MA_SHOWER", "Arrow Shower"},
        {"AM_CANNIBALIZE", "Bio Cannibalize"},
        {"MA_DOUBLE", "Double Strafing"},
        {"MS_BERSERK", "Berserk"},
        {"MS_REFLECTSHIELD", "Reflect Shield"},
        {"AM_SPHEREMINE", "Sphere Mine"},
        {"MS_PARRYING", "Parrying"},
        {"MH_PYROCLASTIC", "Pyroclastic"},
        {"MH_GRANITIC_ARMOR", "Granitic Armor"},
        {"AM_CP_WEAPON", "Chemical Protection Weapon"},
        {"MH_MAGMA_FLOW", "Magma Flow"},
        {"EL_BLAST", "Blast"},
        {"MH_TINDER_BREAKER", "Tinder Breaker"},
        {"AM_CP_SHIELD", "Chemical Protection Shield"},
        {"MH_HEILIGE_STANGE", "Holy Pole"},
        {"MH_GOLDENE_FERSE", "Golden Heel"},
        {"NPC_ALLHEAL", "All Heal"},
        {"AM_CP_ARMOR", "Chemical Protection Armor"},
        {"EL_PETROLOGY", " Petrology"},
        {"MH_SONIC_CRAW", "Sonic Claw"},
        {"MH_SILENT_BREEZE", "Silent Breeze"},
        {"AM_CP_HELM", "Chemical Protection Helm"},
        {"MH_ERASER_CUTTER", "Eraser Cutter"},
        {"MH_OVERED_BOOST", "Overed Boost"},
        {"MH_LIGHT_OF_REGENE", "Light of Regene"},
        {"AM_BIOETHICS", "Bioethics"},
        {"MH_POISON_MIST", "Poison Mist"},
        {"MH_SUMMON_LEGION", "Summon Legion"},
        {"HVAN_EXPLOSION", "Bio Explosion"},
        {"AM_BIOTECHNOLOGY", "Biotechnology"},
        {"SA_CREATECON", "Create Elemental Converter"},
        {"EL_WILD_STORM", "Wild Storm"},
        {"MG_FROSTDIVER", "Frost Diver"},
        {"AM_CREATECREATURE", "Create Creature"},
        {"HFLI_SBR44", "S.B.R.44"},
        {"HFLI_FLEET", "Fleet Move"},
        {"HAMI_BLOODLUST", "Blood Lust"},
        {"AM_CULTIVATION", "Cultivation"},
        {"HAMI_SKIN", "Adamantium Skin"},
        {"EL_CURSED_SOIL", "Cursed Soil"},
        {"HLIF_CHANGE", "Mental Change"},
        {"AM_FLAMECONTROL", "Flame Control"},
        {"HLIF_AVOID", "Emergency Avoid"},
        {"LG_OVERBRAND", "Overbrand"},
        {"ALL_ODINS_RECALL", "Odin's Recall"},
        {"AM_CALLHOMUN", "Call Homunculus"},
        {"SR_RIDEINLIGHTNING", "Ride in Lightning"},
        {"SR_HOWLINGOFLION", "Howling of Lion"},
        {"SR_TIGERCANNON", "Tiger Cannon"},
        {"AM_REST", "Rest"},
        {"GN_CHANGEMATERIAL", "Change Material"},
        {"GN_SLINGITEM", "Sling Item"},
        {"GN_MANDRAGORA", "Howling of Mandragora"},
        {"AM_DRILLMASTER", "Drillmaster"},
        {"GN_HELLS_PLANT", "Hell's Plant"},
        {"GN_FIRE_EXPANSION", "Fire Expansion"},
        {"GN_DEMONIC_FIRE", "Demonic Fire"},
        {"AM_HEALHOMUN", "Heal Homunculus"},
        {"GN_WALLOFTHORN", "Wall of Thorns"},
        {"SR_CRESCENTELBOW", "Crescent Elbow"},
        {"GN_CARTBOOST", "Cart Boost"},
        {"AM_RESURRECTHOMUN", "Resurrect Homunculus"},
        {"GN_CARTCANNON", "Cart Cannon"},
        {"GN_CART_TORNADO", "Cart Tornado"},
        {"GN_TRAINING_SWORD", "Sword Training"},
        {"CR_TRUST", "Faith"},
        {"EL_WATER_SCREW_ATK", "Water Screw"},
        {"EL_WATER_SCREW", "Water Screw"},
        {"EL_ICE_NEEDLE", "Ice Needle"},
        {"CR_AUTOGUARD", "Auto Guard"},
        {"EL_FIRE_WAVE_ATK", "Fire Wave"},
        {"EL_FIRE_WAVE", "Fire Wave"},
        {"EL_FIRE_BOMB_ATK", "Fire Bomb"},
        {"CR_SHIELDCHARGE", "Shield Charge"},
        {"EL_UPHEAVAL", "Upheaval"},
        {"HAMI_DEFENCE", "Defense"},
        {"HVAN_CHAOTIC", "Chaotic Benediction"},
        {"CR_SHIELDBOOMERANG", "Shield Boomerang"},
        {"MH_MIDNIGHT_FRENZY", "Midnight Frenzy"},
        {"MH_EQC", "Eternal Quick Combo"},
        {"EL_GUST", "Gust"},
        {"CR_REFLECTSHIELD", "Reflect Shield"},
        {"EL_CHILLY_AIR", "Cool Air"},
        {"EL_COOLER", "Cooler"},
        {"GD_REGENERATION", "Regeneration"},
        {"CR_HOLYCROSS", "Holy Cross"},
        {"SO_CLOUD_KILL", "Cloud Kill"},
        {"EL_AQUAPLAY", "Aqua Play"},
        {"SO_EL_ACTION", "Elemental Action"},
        {"CR_GRANDCROSS", "Grand Cross"},
        {"SO_WATER_INSIGNIA", "Water Insignia"},
        {"SR_RAISINGDRAGON", "Raising Dragon"},
        {"SR_POWERVELOCITY", "Power Velocity"},
        {"CR_DEVOTION", "Devotion"},
        {"SO_SUMMON_AQUA", "Summon Aqua"},
        {"NV_BASIC", "Basic Skill"},
        {"MG_STONECURSE", "Stone Curse"},
        {"CR_PROVIDENCE", "Providence"},
        {"AB_EUCHARISTICA", "Eucharistica"},
        {"CR_DEFENDER", "Defender"},
        {"AB_SILENTIUM", "Silentium"},
        {"CR_SPEARQUICKEN", "Spear Quicken"},
        {"SO_SUMMON_TERA", "Summon Tera"},
        {"MO_IRONHAND", "Iron Hand"},
        {"SO_SUMMON_VENTUS", "Summon Ventus"},
        {"MO_SPIRITSRECOVERY", "Spirits Recovery"},
        {"SO_EL_ANALYSIS", "Four Spirity Analysis"},
        {"MO_CALLSPIRITS", "Call Spirits"},
        {"SO_VARETYR_SPEAR", "Varetyr Spear"},
        {"MO_ABSORBSPIRITS", "Absorb Spirits"},
        {"SO_VACUUM_EXTREME", "Vacuum Extreme"},
        {"MO_TRIPLEATTACK", "Triple Attack"},
        {"EL_POWER_OF_GAIA", "Power of Gaia"},
        {"MO_BODYRELOCATION", "Body Relocation"},
        {"SR_GENTLETOUCH_ENERGYGAIN", "Gentle Touch - Energy Gain"},
        {"MO_DODGE", "Dodge"},
        {"SO_EARTHGRAVE", "Earth Grave"},
        {"MO_INVESTIGATE", "Investigate"},
        {"SO_SPELLFIST", "Spell Fist"},
        {"MO_FINGEROFFENSIVE", "Finger Offensive"},
        {"SO_ELECTRICWALK", "Electric Walk"},
        {"MO_STEELBODY", "Steel Body"},
        {"WM_UNLIMITED_HUMMING_VOICE", "Unlimited Humming Voice"},
        {"MO_BLADESTOP", "Blade Stop"},
        {"WA_SWING_DANCE", "Swing Dance"},
        {"MO_EXPLOSIONSPIRITS", "Critical Explosion"},
        {"WM_SATURDAY_NIGHT_FEVER", "Saturday Night Fever"},
        {"MO_EXTREMITYFIST", "Asura Strike"},
        {"MG_FIREBALL", "Fire Ball"},
        {"MO_CHAINCOMBO", "Chain Combo"},
        {"WM_SOUND_OF_DESTRUCTION", "Sound of Destruction"},
        {"MO_COMBOFINISH", "Combo Finish"},
        {"WM_DANCE_WITH_WUG", "Dance with a Warg"},
        {"SA_ADVANCEDBOOK", "Advanced Book"},
        {"WM_SONG_OF_MANA", "Song of Mana"},
        {"SA_CASTCANCEL", "Cast Cancel"},
        {"WL_WHITEIMPRISON", "White Imprison"},
        {"SA_MAGICROD", "Magic Rod"},
        {"WL_STASIS", "Stasis"},
        {"SA_SPELLBREAKER", "Spell Breaker"},
        {"WL_TETRAVORTEX", "Tetra Vortex"},
        {"SA_FREECAST", "Free Cast"},
        {"WM_GREAT_ECHO", "Great Echo"},
        {"SA_AUTOSPELL", "Auto Spell"},
        {"RA_ARROWSTORM", "Arrow Storm"},
        {"SA_FLAMELAUNCHER", "Flame Launcher"},
        {"RA_WUGRIDER", "Warg Rider"},
        {"SA_FROSTWEAPON", "Frost Weapon"},
        {"RA_MAGENTATRAP", "Magenta Trap"},
        {"SA_LIGHTNINGLOADER", "Lightning Loader"},
        {"NC_PILEBUNKER", "Pile Bunker"},
        {"SA_SEISMICWEAPON", "Seismic Weapon"},
        {"NC_B_SIDESLIDE", "Back Side Slide"},
        {"SA_DRAGONOLOGY", "Dragonology"},
        {"NC_NEUTRALBARRIER", "Neutral Barrier"},
        {"SA_VOLCANO", "Volcano"},
        {"NC_SILVERSNIPER", "FAW - Silver Sniper"},
        {"SA_DELUGE", "Deluge"},
        {"SC_BODYPAINT", "Body Painting"},
        {"SA_VIOLENTGALE", "Violent Gale"},
        {"MG_FIREWALL", "Fire Wall"},
        {"SA_LANDPROTECTOR", "Land Protector"},
        {"WM_GLOOMYDAY", "Gloomy Day"},
        {"SA_DISPELL", "Dispell"},
        {"LG_FORCEOFVANGUARD", "Force of Vanguard"},
        {"SA_ABRACADABRA", "Abracadabra"},
        {"LG_RAYOFGENESIS", "Ray of Genesis"},
        {"SA_MONOCELL", "Monocell"},
        {"SR_FALLENEMPIRE", "Fallen Empire"},
        {"SA_CLASSCHANGE", "Class Change"},
        {"SR_WINDMILL", "Windmill"},
        {"SA_SUMMONMONSTER", "Summon Monster"},
        {"SR_GENTLETOUCH_CURE", "Gentle Touch (Cure)"},
        {"SA_REVERSEORCISH", "Reverse Orcish"},
        {"WM_LULLABY_DEEPSLEEP", "Deep Sleep Lullaby"},
        {"SA_DEATH", "Death"},
        {"WM_DEADHILLHERE", "Valley of Death"},
        {"SA_FORTUNE", "Fortune"},
        {"WM_SEVERE_RAINSTORM", "Severe Rainstorm"},
        {"SA_TAMINGMONSTER", "Taming Monster"},
        {"MI_RUSH_WINDMILL", "Windmill Swing Attack"},
        {"SA_QUESTION", "?"},
        {"WM_REVERBERATION", "Reverberation"},
        {"SA_GRAVITY", "Gravity"},
        {"WM_METALICSOUND", "Metalic Sound"},
        {"SA_LEVELUP", "Level Up"},
        {"WM_LESSON", "Lesson"},
        {"SA_INSTANTDEATH", "Instant Death"},
        {"MI_ECHOSONG", "Echo Song"},
        {"SA_FULLRECOVERY", "Full Recovery"},
        {"WM_DOMINION_IMPULSE", "Dominion Impulse"},
        {"SA_COMA", "Coma"},
        {"MG_FIREBOLT", "Fire Bolt"},
        {"BD_ADAPTATION", "Adaptation to Circumstances"},
        {"WM_BEYOND_OF_WARCRY", "Warcry of Beyond"},
        {"BD_ENCORE", "Encore"},
        {"SR_GENTLETOUCH_REVITALIZE", "Gentle Touch (Revitalize)"},
        {"BD_LULLABY", "Lullaby"},
        {"SO_PSYCHIC_WAVE", "Psychic Wave"},
        {"BD_RICHMANKIM", "Mr. Kim A Rich Man"},
        {"SO_SUMMON_AGNI", "Summon Agni"},
        {"BD_ETERNALCHAOS", "Eternal Chaos"},
        {"SO_FIRE_INSIGNIA", "Fire Insignia"},
        {"BD_DRUMBATTLEFIELD", "A Drum on the Battlefield"},
        {"SR_CURSEDCIRCLE", "Cursed Circle"},
        {"BD_RINGNIBELUNGEN", "The Ring of Nibelungen"},
        {"GN_SPORE_EXPLOSION", "Spore Explosion"},
        {"BD_ROKISWEIL", "Loki's Veil"},
        {"SR_RAMPAGEBLASTER", "Rampage Blaster"},
        {"BD_INTOABYSS", "Into the Abyss"},
        {"GN_S_PHARMACY", "Special Pharmacy"},
        {"BD_SIEGFRIED", "Invulnerable Siegfried"},
        {"GD_RESTORE", "Restore"},
        {"BD_RAGNAROK", "Ragnarok"},
        {"LG_INSPIRATION", "Inspiration"},
        {"BA_MUSICALLESSON", "Musical Lesson"},
        {"LG_PIETY", "Piety"},
        {"BA_MUSICALSTRIKE", "Musical Strike"},
        {"LG_PRESTIGE", "Prestige"},
        {"BA_DISSONANCE", "Dissonance"},
        {"ALL_ODINS_POWER", "Odin's Power"},
        {"BA_FROSTJOKE", "Frost Joke"},
        {"LG_EXEEDBREAK", "Exceed Break"},
        {"BA_WHISTLE", "A Whistle"},
        {"MG_LIGHTNINGBOLT", "Lightning Bolt"},
        {"BA_ASSASSINCROSS", "Assassin Cross of Sunset"},
        {"LG_RAGEBURST", "Rage Burst"},
        {"BA_POEMBRAGI", "A Poem of Bragi"},
        {"ML_DEVOTION", "Devotion"},
        {"BA_APPLEIDUN", "The Apple of Idun"},
        {"LG_TRAMPLE", "Trample"},
        {"DC_DANCINGLESSON", "Dancing Lesson"},
        {"SC_MAELSTROM", "Maelstrom"},
        {"DC_THROWARROW", "Throw Arrow"},
        {"SC_CHAOSPANIC", "Chaos Panic"},
        {"DC_UGLYDANCE", "Ugly Dance"},
        {"SC_DIMENSIONDOOR", "Dimension Door"},
        {"DC_SCREAM", "Scream"},
        {"SC_MANHOLE", "Manhole"},
        {"DC_HUMMING", "Humming"},
        {"EL_PYROTECHNIC", "Pyrotechnic"},
        {"DC_DONTFORGETME", "Please Don't Forget Me"},
        {"SC_WEAKNESS", "Masquerade - Weakness"},
        {"DC_FORTUNEKISS", "Fortune's Kiss"},
        {"SC_UNLUCKY", "Masquerade - Unlucky"},
        {"DC_SERVICEFORYOU", "Service for You"},
        {"SC_IGNORANCE", "Masquerade - Ignorance"},
        {"SC_GROOMY", "Masquerade - Groomy"},
        {"SC_INVISIBILITY", "Invisibility"},
        {"SC_AUTOSHADOWSPELL", "Auto Shadow Spell"},
        {"SC_REPRODUCE", "Reproduce"},
        {"SC_FATALMENACE", "Fatal Menace"},
        {"NC_MAGICDECOY", "FAW - Magic Decoy"},
        {"WE_MALE", "I'll save you"},
        {"NC_AXEBOOMERANG", "Axe Boomerang"},
        {"WE_FEMALE", "I'll sacrifice myself for you"},
        {"MG_THUNDERSTORM", "Thunder Storm"},
        {"WE_CALLPARTNER", "I miss you"},
        {"NC_RESEARCHFE", "Research Fire / Earth"},
        {"ITM_TOMAHAWK", "Throw Tomahawk"},
        {"NC_STEALTHFIELD", "Stealth Field"},
        {"NC_INFRAREDSCAN", "Infrared Scan"},
        {"NC_EMERGENCYCOOL", "Emergency Cool"},
        {"NC_SHAPESHIFT", "Shape Shift"},
        {"NC_SELFDESTRUCTION", "Self Destruction"},
        {"NC_MAINFRAME", "Mainframe Restructure"},
        {"NC_ACCELERATION", "Acceleration"},
        {"NC_ARMSCANNON", "Arms Cannon"},
        {"NC_VULCANARM", "Vulcan Arm"},
        {"RA_ICEBOUNDTRAP", "Ice Bound Trap"},
        {"RA_FIRINGTRAP", "Firing Trap"},
        {"RA_VERDURETRAP", "Verdure Trap"},
        {"RA_COBALTTRAP", "Cobalt Trap"},
        {"RA_SENSITIVEKEEN", "Sensitive Keen"},
        {"RA_TOOTHOFWUG", "Tooth of Warg"},
        {"RA_WUGDASH", "Warg Dash"},
        {"RA_ELECTRICSHOCKER", "Electric Shocker"},
        {"RA_DETONATOR", "Detonator"},
        {"RA_AIMEDBOLT", "Aimed Bolt"},
        {"RA_RANGERMAIN", "Ranger Main"},
        {"RA_FEARBREEZE", "Fear Breeze"},
        {"WL_RELEASE", "Release"},
        {"WL_SUMMONSTONE", "Summon Stone"},
        {"WL_SUMMONFB", "Summon Fire Ball"},
        {"WL_CHAINLIGHTNING", "Chain Lightning"},
        {"WL_COMET", "Comet"},
        {"WL_DRAINLIFE", "Drain Life"},
        {"WL_RECOGNIZEDSPELL", "Recognized Spell"},
        {"AL_DP", "Divine Protection"},
        {"WL_MARSHOFABYSS", "Marsh of Abyss"},
        {"WL_JACKFROST", "Jack Frost"},
        {"WL_FROSTMISTY", "Frost Misty"},
        {"WL_SOULEXPANSION", "Soul Expansion"},
        {"AB_DUPLELIGHT", "Duple Light"},
        {"AB_EXPIATIO", "Expiatio"},
        {"LK_AURABLADE", "Aura Blade"},
        {"AB_RENOVATIO", "Renovatio"},
        {"LK_PARRYING", "Parrying"},
        {"AB_LAUDAAGNUS", "Lauda Agnus"},
        {"LK_CONCENTRATION", "Concentration"},
        {"AB_ORATIO", "Oratio"},
        {"LK_TENSIONRELAX", "Tension Relax"},
        {"AB_PRAEFATIO", "Praefatio"},
        {"LK_BERSERK", "Berserk"},
        {"AB_EPICLESIS", "Epiclesis"},
        {"AB_CHEAL", "Coluceo Heal"},
        {"AB_ANCILLA", "Ancilla"},
        {"HP_ASSUMPTIO", "Assumptio"},
        {"GC_HALLUCINATIONWALK", "Hallucination Walk"},
        {"HP_BASILICA", "Basilica"},
        {"GC_VENOMPRESSURE", "Venom Pressure"},
        {"HP_MEDITATIO", "Meditatio"},
        {"GC_WEAPONCRUSH", "Weapon Crush"},
        {"HW_SOULDRAIN", "Soul Drain"},
        {"GC_POISONINGWEAPON", "Poisoning Weapon"},
        {"HW_MAGICCRASHER", "Magic Crasher"},
        {"GC_DARKILLUSION", "Dark Illusion"},
        {"HW_MAGICPOWER", "Amplify Magic Power"},
        {"RK_ABUNDANCE", "Abundance"},
        {"PA_PRESSURE", "Pressure"},
        {"AL_DEMONBANE", "Demon Bane"},
        {"PA_SACRIFICE", "Sacrifice"},
        {"RK_STONEHARDSKIN", "Stonehard Skin"},
        {"PA_GOSPEL", "Gospel"},
        {"RK_GIANTGROWTH", "Giant Growth"},
        {"CH_PALMSTRIKE", "Palm Push Strike"},
        {"RK_MILLENNIUMSHIELD", "Millennium Shield"},
        {"CH_TIGERFIST", "Tiger Knuckle Fist"},
        {"RK_DRAGONTRAINING", "Dragon Training"},
        {"CH_CHAINCRUSH", "Chain Crush Combo"},
        {"RK_DEATHBOUND", "Death Bound"},
        {"PF_HPCONVERSION", "Health Conversion"},
        {"HVAN_INSTRUCT", "Change Instruction"},
        {"PF_SOULCHANGE", "Soul Change"},
        {"MH_STAHL_HORN", "Steel's Horn"},
        {"PF_SOULBURN", "Soul Burn"},
        {"NPC_MAGICMIRROR", "Magic Mirror"},
        {"ASC_KATAR", "Advanced Katar Research"},
        {"DA_DREAM", "Black Dream Of Gemstone"},
        {"DA_SPACE", "Dark Twilight"},
        {"GD_EMERGENCYCALL", "Emergency Call"},
        {"ASC_EDP", "Enchant Deadly Poison"},
        {"DE_NIGHTMARE", "Death Nightmare"},
        {"ASC_BREAKER", "Soul Breaker"},
        {"SL_GUNNER", "Gunslinger Spirit"},
        {"SN_SIGHT", "True Sight"},
        {"MB_MUNAKKNOWLEDGE", "Taming Master"},
        {"SN_FALCONASSAULT", "Falcon Assault"},
        {"NJ_NEN", "Soul"},
        {"SN_SHARPSHOOTING", "Sharp Shooting"},
        {"NJ_TATAMIGAESHI", "Reverse Tatami"},
        {"GS_CHAINACTION", "Chain Action"},
        {"KO_YAMIKUMO", "Shadow Cloud"},
        {"KO_RIGHT", "Right Hand Mastery"},
        {"KO_LEFT", "Left Hand Mastery"},
        {"KO_JYUMONJIKIRI", "Cross Strike"},
        {"KO_SETSUDAN", "Setsudan"},
        {"KO_BAKURETSU", "Exploding Kunai"},
        {"KO_HAPPOKUNAI", " Happo Kunai"},
        {"KO_MUCHANAGE", "Overthrow"},
        {"KO_HUUMARANKA", "Huuma Ranka"},
        {"KO_MAKIBISHI", "Makibishi"},
        {"KO_MEIKYOUSISUI", "Meikyousisui"},
        {"KO_ZANZOU", "Illusion - Afterimage"},
        {"KO_KYOUGAKU", "Illusion - Shock"},
        {"KO_JYUSATSU", "Illusion - Killing Curse"},
        {"KO_KAHU_ENTEN", "Kahu Enten"},
        {"KO_HYOUHU_HUBUKI", "Hyouhu Hubuki"},
        {"KO_KAZEHU_SEIRAN", "Kazehu Seiran"},
        {"KO_DOHU_KOUKAI", "Dohu Koukai"},
        {"KO_KAIHOU", "Technique Kaihou"},
        {"KO_ZENKAI", "Zenkai"},
        {"KO_GENWAKU", "Genwaku"},
        {"KO_IZAYOI", "16th Night"},
        {"KG_KAGEHUMI", "Shadow Step"},
        {"KG_KYOMU", "Kyomu"},
        {"KG_KAGEMUSYA", "Shadow Warrior"},
        {"OB_ZANGETSU", "Distorted Crescent Moon"},
        {"OB_OBOROGENSOU", "Oboro Gensou"},
        {"OB_AKAITSUKI", "Ominous Crimson Moonlight"},
        {"ECLAGE_RECALL", "Return to Eclage"},
        {"ECL_SNOWFLIP", "Snow Flip"},
        {"ECL_SEQUOIADUST", "Sequoia Dust"},
    };
    if (auto it = kNames.find(internalName); it != kNames.end()) return it->second;
    return internalName;  // fallback: unmapped -> show the internal name
}

}  // namespace uaro::net
