#!/usr/bin/env python3
# Regenerate Client/src/game/AccessorySprites.cpp from data.grf's accessoryid.lub
# + accname.lub (headgear view-id -> sprite name). Same Lua 5.1 bytecode shape as
# the NPC tables (see gen_actor_sprites.py): accessoryid sets ACCESSORY_IDs[NAME]=id,
# accname sets AccNameTable[ACCESSORY_IDs.NAME]="_spritename". We recover both by
# tracking LOADK/GETTABLE/SETTABLE register flow and join on the constant name.
#
#   usage: python3 tools/gen_accessory_sprites.py accessoryid.lub accname.lub
import struct
import sys


class R:
    def __init__(s, d):
        s.d = d
        s.p = 12

    def u8(s):
        v = s.d[s.p]
        s.p += 1
        return v

    def u32(s):
        v = struct.unpack_from("<I", s.d, s.p)[0]
        s.p += 4
        return v

    def dbl(s):
        v = struct.unpack_from("<d", s.d, s.p)[0]
        s.p += 8
        return v

    def st(s):
        n = s.u32()
        if n == 0:
            return None
        b = s.d[s.p : s.p + n]
        s.p += n
        return b[:-1]


def proto(r):
    r.st()
    r.u32()
    r.u32()
    r.u8()
    r.u8()
    r.u8()
    r.u8()
    code = [r.u32() for _ in range(r.u32())]
    K = []
    for _ in range(r.u32()):
        t = r.u8()
        K.append(None if t == 0 else bool(r.u8()) if t == 1 else r.dbl() if t == 3 else r.st())
    [proto(r) for _ in range(r.u32())]
    n = r.u32()
    [r.u32() for _ in range(n)]
    n = r.u32()
    [(r.st(), r.u32(), r.u32()) for _ in range(n)]
    n = r.u32()
    [r.st() for _ in range(n)]
    return code, K


def dec(i):
    return i & 0x3F, (i >> 6) & 0xFF, (i >> 23) & 0x1FF, (i >> 14) & 0x1FF, (i >> 14) & 0x3FFFF


def load(fn):
    return proto(R(open(fn, "rb").read()))


def rk(K, reg, x):
    return K[x & 0xFF] if (x & 0x100) else reg.get(x)


code, K = load(sys.argv[1])
reg, name2id = {}, {}
for ins in code:
    op, A, B, C, Bx = dec(ins)
    if op == 1:
        reg[A] = K[Bx]
    elif op == 9:
        k, v = rk(K, reg, B), rk(K, reg, C)
        if isinstance(k, bytes) and isinstance(v, float):
            name2id[k] = int(v)
    elif op in (5, 6, 10, 36):
        reg[A] = None

code, K = load(sys.argv[2])
reg, name2spr = {}, {}
for ins in code:
    op, A, B, C, Bx = dec(ins)
    if op == 1:
        reg[A] = K[Bx]
    elif op == 6:
        k = rk(K, reg, C)
        reg[A] = ("k", k) if isinstance(k, bytes) else None
    elif op == 9:
        key, val = rk(K, reg, B), rk(K, reg, C)
        if isinstance(key, tuple) and key[0] == "k" and isinstance(val, bytes):
            name2spr[key[1]] = val
    elif op in (5, 10, 36):
        reg[A] = None

id2spr = {name2id[n]: s for n, s in name2spr.items() if n in name2id}
items = sorted(id2spr.items())

SAFE = set(b"abcdefghijklmnopqrstuvwxyz0123456789_")


def cstr(b):
    out = []
    for ch in b:
        lc = ch + 32 if 0x41 <= ch <= 0x5A else ch
        out.append(chr(lc) if lc in SAFE else "\\%03o" % ch)
    return '"' + "".join(out) + '"'


out = [
    "// GENERATED by tools/gen_accessory_sprites.py from data.grf's accessoryid.lub",
    "// + accname.lub. Maps a headgear view id to its accessory sprite name (EUC-KR,",
    "// octal-escaped); the loader resolves data/sprite/<accessory>/<sex>/<sex><name>.",
    '#include "game/AccessorySprites.hpp"',
    "",
    "#include <algorithm>",
    "",
    "namespace uaro {",
    "namespace {",
    "struct Entry { u16 id; const char* name; };",
    "constexpr Entry kTable[] = {",
]
line = "    "
for i, nm in items:
    tok = "{%d,%s}," % (i, cstr(nm))
    if len(line) + len(tok) > 100:
        out.append(line)
        line = "    "
    line += tok
if line.strip():
    out.append(line)
out += [
    "};",
    "} // namespace",
    "",
    "const char* accessoryName(u16 id) {",
    "    const auto* end = kTable + (sizeof(kTable) / sizeof(kTable[0]));",
    "    const auto* it = std::lower_bound(kTable, end, id,",
    "                                      [](const Entry& e, u16 v) { return e.id < v; });",
    "    return (it != end && it->id == id) ? it->name : nullptr;",
    "}",
    "",
    "} // namespace uaro",
]
open("src/game/AccessorySprites.cpp", "w").write("\n".join(out) + "\n")
print("wrote src/game/AccessorySprites.cpp with %d entries" % len(items))
