import os
OUT="/root/uAthena/Client/src/ui/EmbeddedFonts.cpp"
fonts = [
  ("kEmbeddedThaiTtf",       "noto_thai.ttf"),
  ("kEmbeddedArabicTtf",     "noto_arabic.ttf"),
  ("kEmbeddedHebrewTtf",     "noto_hebrew.ttf"),
  ("kEmbeddedDevanagariTtf", "noto_deva.ttf"),
  ("kEmbeddedCjkTtf",        "NotoSansCJKsub.otf"),
]
with open(OUT,"w") as o:
    o.write("// Auto-generated by tools/gen_embedded_fonts.py -- do not edit by hand.\n")
    o.write("// Per-script fallback faces baked into the exe so ALL languages render from a bare\n")
    o.write("// binary with no external font files (S.: \"все шрифты в exe\"). Small scripts are full;\n")
    o.write("// the CJK face is subset to the codepoints used by zh/zh_TW/ja/ko texts (UI-complete).\n")
    o.write("#include <cstddef>\n\nnamespace uaro {\n\n")
    for name, path in fonts:
        data = open(path,"rb").read()
        o.write(f"extern const unsigned char {name}[] = {{\n")
        line=[]
        for i,b in enumerate(data):
            line.append(str(b))
            if len(line)==24:
                o.write("    "+",".join(line)+",\n"); line=[]
        if line: o.write("    "+",".join(line)+",\n")
        o.write("};\n")
        o.write(f"extern const std::size_t {name}Size = sizeof({name});\n\n")
    o.write("}  // namespace uaro\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
