import glob, os, sys
# Paths are overridable via argv (CMake passes them) so this works on any checkout, not just /root.
# Fallback to repo-relative defaults derived from this script's location, then the old absolutes.
_here = os.path.dirname(os.path.abspath(__file__))
_default_texts = os.path.normpath(os.path.join(_here, "..", "assets", "texts"))
_default_out = os.path.normpath(os.path.join(_here, "..", "src", "app", "EmbeddedTexts.cpp"))
TEXTS = sys.argv[1] if len(sys.argv) > 1 else _default_texts
OUT = sys.argv[2] if len(sys.argv) > 2 else _default_out
files=sorted(glob.glob(os.path.join(TEXTS,"*.cfg")))
with open(OUT,"w") as o:
    o.write("// Auto-generated by tools/gen_embedded_texts.py -- do not edit by hand.\n")
    o.write("// All UI translation tables (texts/<code>.cfg) baked into the exe so every language works\n")
    o.write("// from a bare binary with no external text files (S.: \"залей файлы переводов в exe\").\n")
    o.write("#include <cstddef>\n#include <string>\n\nnamespace uaro {\n\n")
    entries=[]
    for f in files:
        code=os.path.splitext(os.path.basename(f))[0]
        sym="t_"+code.replace("-","_")
        data=open(f,"rb").read()
        o.write(f"static const unsigned char {sym}[] = {{\n")
        line=[]
        for b in data:
            line.append(str(b))
            if len(line)==24: o.write("    "+",".join(line)+",\n"); line=[]
        if line: o.write("    "+",".join(line)+",\n")
        o.write("};\n\n")
        entries.append((code,sym))
    o.write("struct EmbTxt { const char* code; const unsigned char* data; std::size_t size; };\n")
    o.write("static const EmbTxt kEmbTexts[] = {\n")
    for code,sym in entries:
        o.write(f'    {{"{code}", {sym}, sizeof({sym})}},\n')
    o.write("};\n\n")
    o.write("// Returns the embedded cfg bytes for a language code (\"en\",\"ru\",...) or nullptr; sets size.\n")
    o.write("const char* embedded_text(const std::string& code, std::size_t& size) {\n")
    o.write("    for (const auto& e : kEmbTexts)\n")
    o.write("        if (code == e.code) { size = e.size; return reinterpret_cast<const char*>(e.data); }\n")
    o.write("    size = 0;\n    return nullptr;\n}\n\n")
    o.write("}  // namespace uaro\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes;", len(files), "languages")
