#!/usr/bin/env python3
# Regenerate Client/src/game/ActorSprites.cpp from the client's compiled Lua tables
# (npcidentity.lub + jobname.lub) in data.grf, giving NPC/monster view-id -> sprite
# name. The two .lub files are Lua 5.1 bytecode; we statically recover the
# jobtbl[JT_x]=id and JobNameTable[jobtbl.JT_x]="name" assignments by tracking
# LOADK/GETTABLE/SETTABLE register flow (no Lua VM needed).
#
#   usage: python3 tools/gen_actor_sprites.py npcidentity.lub jobname.lub
import struct, sys
class R:
    def __init__(s,d): s.d=d; s.p=12  # skip 12-byte header
    def u8(s): v=s.d[s.p]; s.p+=1; return v
    def u32(s): v=struct.unpack_from('<I',s.d,s.p)[0]; s.p+=4; return v
    def dbl(s): v=struct.unpack_from('<d',s.d,s.p)[0]; s.p+=8; return v
    def st(s):
        n=s.u32()
        if n==0: return None
        b=s.d[s.p:s.p+n]; s.p+=n; return b[:-1]
def proto(r):
    r.st(); r.u32(); r.u32(); r.u8(); r.u8(); r.u8(); r.u8()
    code=[r.u32() for _ in range(r.u32())]
    K=[]
    for _ in range(r.u32()):
        t=r.u8()
        K.append(None if t==0 else bool(r.u8()) if t==1 else r.dbl() if t==3 else r.st())
    [proto(r) for _ in range(r.u32())]
    n=r.u32(); [r.u32() for _ in range(n)]
    n=r.u32(); [(r.st(),r.u32(),r.u32()) for _ in range(n)]
    n=r.u32(); [r.st() for _ in range(n)]
    return code,K
def dec(i): return i&0x3f,(i>>6)&0xff,(i>>23)&0x1ff,(i>>14)&0x1ff,(i>>14)&0x3ffff
def load(fn): return proto(R(open(fn,'rb').read()))
def rk(K,reg,x): return K[x&0xff] if (x&0x100) else reg.get(x)

code,K=load(sys.argv[1]); reg={}; jt2id={}
for ins in code:
    op,A,B,C,Bx=dec(ins)
    if op==1: reg[A]=K[Bx]
    elif op==9:
        k=rk(K,reg,B); v=rk(K,reg,C)
        if isinstance(k,bytes) and isinstance(v,float): jt2id[k]=int(v)
    elif op in (5,6,10,36): reg[A]=None
code,K=load(sys.argv[2]); reg={}; jt2name={}
for ins in code:
    op,A,B,C,Bx=dec(ins)
    if op==1: reg[A]=K[Bx]
    elif op==6:
        k=rk(K,reg,C); reg[A]=('jt',k) if isinstance(k,bytes) else None
    elif op==9:
        key=rk(K,reg,B); val=rk(K,reg,C)
        if isinstance(key,tuple) and key[0]=='jt' and isinstance(val,bytes): jt2name[key[1]]=val
    elif op in (5,10,36): reg[A]=None
id2name={jt2id[jt]:nm for jt,nm in jt2name.items() if jt in jt2id}  # nm is raw bytes
items=sorted(id2name.items())

SAFE=set(b"abcdefghijklmnopqrstuvwxyz0123456789_")
def cstr(b):
    # Lowercase ASCII (the VFS lowercases ASCII only); emit anything outside the
    # safe set as 3-digit octal so EUC-KR bytes and backslashes survive in the
    # C string literal without being read as escapes.
    out=[]
    for ch in b:
        lc = ch + 32 if 0x41 <= ch <= 0x5A else ch
        out.append(chr(lc) if lc in SAFE else "\\%03o" % ch)
    return '"' + "".join(out) + '"'

out=["// GENERATED by tools/gen_actor_sprites.py from data.grf's npcidentity.lub +",
     "// jobname.lub. Maps an NPC/monster view id to its sprite base name; the loader",
     "// resolves it under data/sprite/npc/ or the EUC-KR monster sprite folder.",
     '#include "game/ActorSprites.hpp"','','#include <algorithm>','',
     "namespace uaro {","namespace {","struct Entry { u16 id; const char* name; };",
     "constexpr Entry kTable[] = {"]
line="    "
for i,nm in items:
    tok='{%d,%s},'%(i,cstr(nm))
    if len(line)+len(tok)>100: out.append(line); line="    "
    line+=tok
if line.strip(): out.append(line)
out += ["};","} // namespace","",
 "const char* actorSpriteName(u16 id) {",
 "    const auto* end = kTable + (sizeof(kTable) / sizeof(kTable[0]));",
 "    const auto* it = std::lower_bound(kTable, end, id,",
 "                                      [](const Entry& e, u16 v) { return e.id < v; });",
 "    return (it != end && it->id == id) ? it->name : nullptr;","}","",
 "} // namespace uaro"]
open("src/game/ActorSprites.cpp","w").write("\n".join(out)+"\n")
print("wrote src/game/ActorSprites.cpp with %d entries"%len(items))
