# Generates a C++ TU that bakes the compiled sprite shader bytecode into the binary and registers
# it with render/EmbeddedShaders.cpp. Run via `cmake -P`, driven by EmbedSpriteShaders.cmake.
#
# Inputs (via -D):
#   INROOT    root of the compiled shaders (_compiled_shaders); expects <INROOT>/<profile>/<name>.bin
#   OUT       path of the .cpp to write
#   PROFILES  ';'-separated renderer profiles (e.g. "dx11;glsl;spirv")
#   NAMES     ';'-separated shader names   (e.g. "vs_sprite;fs_sprite")
#
# Missing .bin files are skipped (a profile may not have been compiled on this platform), so the
# registry only holds what actually exists.

set(_body "")
set(_init "")
set(_idx 0)
foreach(_p IN LISTS PROFILES)
  foreach(_n IN LISTS NAMES)
    set(_bin "${INROOT}/${_p}/${_n}.bin")
    if(EXISTS "${_bin}")
      file(READ "${_bin}" _hex HEX)
      string(LENGTH "${_hex}" _hexlen)
      math(EXPR _bytes "${_hexlen} / 2")
      # Turn "aabbcc" into "0xaa,0xbb,0xcc,"
      string(REGEX REPLACE "(..)" "0x\\1," _arr "${_hex}")
      set(_sym "g_emb_${_idx}")
      string(APPEND _body "static const unsigned char ${_sym}[] = {${_arr}};\n")
      string(APPEND _init "    register_embedded_shader(\"${_p}/${_n}\", ${_sym}, ${_bytes}u);\n")
      math(EXPR _idx "${_idx} + 1")
    endif()
  endforeach()
endforeach()

set(_out "// Auto-generated by cmake/bin2c_shaders.cmake — do not edit.\n")
string(APPEND _out "#include \"core/Types.hpp\"\n\n")
string(APPEND _out "namespace uaro {\n")
string(APPEND _out "void register_embedded_shader(const char* key, const unsigned char* data, u32 size);\n\n")
string(APPEND _out "${_body}\n")
string(APPEND _out "namespace {\nstruct EmbeddedShaderReg {\n  EmbeddedShaderReg() {\n${_init}  }\n};\n")
string(APPEND _out "static EmbeddedShaderReg s_embeddedShaderReg;\n}  // namespace\n\n")
string(APPEND _out "}  // namespace uaro\n")

file(WRITE "${OUT}" "${_out}")
message(STATUS "bin2c_shaders: wrote ${OUT} (${_idx} shader blob(s))")
